services:
  prometheus-backend:
    image: prometheus-backend
    container_name: prometheus-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
  
  postgresql:
    image: postgres:bullseye
    container_name: prometheus_postgresql
    env_file:
      - .env